# Generated by Django 3.2.9 on 2022-01-19 08:10

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('tel_no', models.IntegerField()),
                ('profile_picture', cloudinary.models.CloudinaryField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Counsellor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('tel_no', models.IntegerField()),
                ('clients', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='councelapp.client')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('members', models.IntegerField()),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='councelapp.counsellor')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='councelapp.group'),
        ),
    ]
