# Generated by Django 3.2.9 on 2022-01-20 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('councelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Counsellor',
            new_name='Counselor',
        ),
    ]
