# Generated by Django 3.2.9 on 2022-01-24 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('councelapp', '0004_alter_counsellor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='councelapp.details'),
        ),
    ]
