# Generated by Django 3.2.9 on 2022-01-24 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('councelapp', '0006_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='consellor',
            new_name='counsellor',
        ),
    ]
