# Generated by Django 3.2.9 on 2022-01-30 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('councelapp', '0009_alter_group_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counsellor',
            old_name='user',
            new_name='account',
        ),
    ]
