# Generated by Django 3.2.9 on 2022-01-30 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('councelapp', '0011_rename_account_counsellor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counsellor',
            name='details',
        ),
        migrations.RemoveField(
            model_name='details',
            name='owner',
        ),
        migrations.AddField(
            model_name='details',
            name='counsellor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='councelapp.counsellor'),
        ),
    ]
