# Generated by Django 3.2.9 on 2022-01-30 18:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('councelapp', '0012_auto_20220130_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
