# Generated by Django 3.2.9 on 2022-01-30 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('councelapp', '0013_counsellor_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counsellor',
            name='profile_pic',
        ),
    ]
