# Generated by Django 3.2.9 on 2022-01-31 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('councelapp', '0014_remove_counsellor_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='counsellor',
        ),
        migrations.AddField(
            model_name='counsellor',
            name='details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='councelapp.details'),
        ),
    ]
