# Generated by Django 3.2.9 on 2022-01-31 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('councelapp', '0015_auto_20220131_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='quantiles',
            new_name='qualities',
        ),
    ]
