# Generated by Django 3.2.9 on 2022-02-01 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('councelapp', '0016_rename_quantiles_details_qualities'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField()),
                ('client', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='councelapp.client')),
            ],
        ),
    ]
