# Generated by Django 3.2.9 on 2022-02-01 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('councelapp', '0017_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='chat',
            name='Text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='councelapp.text'),
        ),
    ]
