# Generated by Django 3.2.9 on 2022-02-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councelapp', '0020_groupchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='time_sent',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
