# Generated by Django 3.2.9 on 2022-02-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councelapp', '0021_groupchat_time_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='time_sent',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
