# Generated by Django 3.2.9 on 2022-02-02 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('councelapp', '0025_chat_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='counsellor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='councelapp.counsellor'),
        ),
    ]
