# Generated by Django 3.2.9 on 2022-02-02 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('councelapp', '0026_chat_counsellor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='counsellor',
        ),
    ]
