# Generated by Django 3.2.9 on 2022-02-02 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('councelapp', '0027_remove_chat_counsellor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chat',
        ),
    ]
