# Generated by Django 3.2.9 on 2022-02-03 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('councelapp', '0028_delete_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Topic', models.TextField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='councelapp.client')),
            ],
        ),
    ]
