# Generated by Django 3.2.9 on 2022-02-03 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('councelapp', '0030_alter_appointment_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Topic',
            new_name='topic',
        ),
    ]
