# Generated by Django 3.2.9 on 2022-02-03 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('councelapp', '0031_rename_topic_appointment_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='councelapp.client'),
        ),
    ]
