# Generated by Django 3.2.9 on 2022-02-03 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('councelapp', '0033_alter_appointment_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='client',
            new_name='user',
        ),
    ]
