# Generated by Django 3.2.9 on 2022-01-19 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsel_users', '0002_account_counsellor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='counsellor',
            new_name='is_counsellor',
        ),
    ]
