# Generated by Django 3.2.9 on 2022-01-30 18:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsel_users', '0003_rename_counsellor_account_is_counsellor'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
